### ISSUE TITLE
SyntaxError in task.py Line 340 During Component Import

### ISSUE THREAD

**Issue by shrysp** [mainframecomputer/orchestra#8]
![CleanShot 2024-12-20 at 19 10 05@2x](https://github.com/user-attachments/assets/9d285518-459e-4155-bf53-c6fdbf9a336a)
I encountered a SyntaxError when trying to import components from the mainframe_orchestra package. The error traceback suggests the issue lies in task.py at line 340.

SyntaxError: f-string: unmatched '('

**Comment by shivkanthb** [comment]
Hey @shrysp! thanks for filing the task. Looks like you were testing it out on google collab? Colab uses a specific implementation of IPython that doesn't handle complex f-strings. However we have fixed the issue to make it work consistently on all environments. Try it out now and lmk if works.

**Comment by shivkanthb** [comment]
Safe to assume this issue has been resolved. In case it is not, please feel free to re-open :)
